// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using WaterQualityMonitor.API.Data;

#nullable disable

namespace WaterQualityMonitor.API.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("WaterQualityMonitor.API.Models.Line", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("Location").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.HasKey("Id");
            b.ToTable("Lines");
            b.HasData(
                new { Id = 1, Location = "Plant North Wing", Name = "Line A" },
                new { Id = 2, Location = "Plant South Wing", Name = "Line B" });
        });

        modelBuilder.Entity("WaterQualityMonitor.API.Models.Threshold", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<int>("LineId").HasColumnType("int");
            b.Property<double>("MaxValue").HasPrecision(10, 4).HasColumnType("float(10)");
            b.Property<double>("MinValue").HasPrecision(10, 4).HasColumnType("float(10)");
            b.Property<string>("ParameterName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("LineId");
            b.ToTable("Thresholds");
            b.HasData(
                new { Id = 1, LineId = 1, MaxValue = 8.5, MinValue = 6.5, ParameterName = "pH" },
                new { Id = 2, LineId = 1, MaxValue = 4.0, MinValue = 0.0, ParameterName = "Turbidity" },
                new { Id = 3, LineId = 1, MaxValue = 800.0, MinValue = 100.0, ParameterName = "Conductivity" },
                new { Id = 4, LineId = 2, MaxValue = 8.5, MinValue = 6.5, ParameterName = "pH" },
                new { Id = 5, LineId = 2, MaxValue = 4.0, MinValue = 0.0, ParameterName = "Turbidity" },
                new { Id = 6, LineId = 2, MaxValue = 800.0, MinValue = 100.0, ParameterName = "Conductivity" });
        });
#pragma warning restore 612, 618
    }
}
